### PR TITLE
bump context version to 2021.03.05

### PR DESCRIPTION
**Pull request by reviczky**
Update debian files for ConTeXt version to 2021.03.05 from TeX Live 2021.

Accompanying PR: https://github.com/debian-tex/context/pull/7

### CODE REVIEW

**Comment by reviczky** [comment]
Standards version checklist:
https://www.debian.org/doc/debian-policy/upgrading-checklist.html#version-4-6-0

**Review by hpreusse — APPROVED** [review]

**Comment by hpreusse** [comment]
I took over the whitespace commit, the changelog and the base commit do conflict currently. Thanks.
Please confirm that standards version bump has been validated with the Debian Policy.

**Comment by reviczky** [comment]
Thanks for that, please wait for the standards version, that needs actually some changes.
I will go through that and submit a new PR.

**Comment by hpreusse** [comment]
According to last update this PR has been merged already somehow. Closing then.

**Pull request closed without merging**
